export interface Persona{
    id: number,
    id_autor: string,
    id_qr: string,
    nivel: string,
    foto: string,
    nombre: string,
    apellido: string,
    ciudad: string,
    direccion: string,
    email: string,
    fechanac: Date,
    nacionalidad: string,
    observaciones: string,
    red: string,
    nombreresp: string,
    telresp: string,
    wspresp: string,
    estado: string,
    obsestado: string,
    fechaestado:string
}

export interface mascota{
    id: number,
    id_autor: string,
    id_qr: string,
    nivel: string,
    foto: string,
    especie: string,
    nombre: string,
    ciudad: string,
    direccion: string,
    fechanac: Date,
    nacionalidad: string,
    observaciones: string,
    nombreresp: string,
    telresp: string,
    wspresp: string,
    estado: string,
    obsestado: string,
    fechaestado:string
}

export interface Vehiculo{
    id: number,
    id_autor: string,
    id_qr: string,
    nivel: string,
    foto: string,
    marca: string,
    modelo: string,
    color: string,
    patente: string,
    ciudad: string,
    anio: string,
    aseguradora: string,
    nroseguro: string,
    observaciones: string,
    nombreresp: string,
    telresp: string,
    wspresp: string,
    estado: string,
    obsestado: string,
    fechaestado:string
}