 export interface em_cards{
    tipo: string,
    icono: string,
    titulo: string,
    contenido: any[]
 }

 export const emergencias_data:em_cards[] = [
    {
        tipo: 'personas',
        icono: '../../../../../../assets/img/emergency/er-phone.png',
        titulo: 'Teléfonos útiles',
        contenido: [
            {title: '911', subtitle: 'Central de Emergencias Nacional', body: 'El 911 es un servicio gratuito provincial que permite la recepción de llamadas desde teléfonos fijos y móviles. Centraliza todas las emergencias relacionadas a Bomberos, Comando Radioeléctrico, Defensa Civil, entre otros.'},
            {title: '107', subtitle: 'Emergencias médicas', body: 'Línea gratuita del servicio público de emergencias médicas. Ambulancia SIES.'},
            {title: '100', subtitle: 'Bomberos', body: 'Los bomberos de Argentina están capacitados para apagar incendios en casas, complejos habitacionales, residenciales, locales comerciales y plantas industriales.'},
            {title: '103', subtitle: 'Defensa civil', body: 'Defensa Civil de Argentina ayuda a los damnificados de terremotos, tsunamis, inundaciones, desprendimientos de tierra, derrame de sustancias químicas y otro tipo de desastres brindándoles medicina, vestimenta, refugios y asistencia médica.'},
            {title: '105', subtitle: 'Emergencia Ambiental', body: 'Frente a una catástrofe resultado de factores naturales, tecnológicos o provocados por el hombre podés recurrir al 105.'},
            {title: '106', subtitle: 'Emergencia Náutica', body: 'Número para comunicarse con Prefectura Naval Argentina.'},
            {title: '135', subtitle: 'Asistencia al Suicida', body: 'Si vos o alguien cercano está atravesando una crisis emocional de cualquier tipo, siente que nada tiene sentido o se encuentra atrapado en una situación a la que no le encuentra salida, no dudes en llamar a éste número.'},
            {title: '142', subtitle: 'Chicos y chicas extraviados', body: 'Frente a una desaparición, llamá a este número. Recordá que no hace falta esperar ningún plazo para realizar la denuncia.'},
            {title: '0800 444 0420', subtitle: 'Violencia familiar y de género', body: 'Si sabés de algún caso de violencia familiar o de género, no dudes en llamar a este número.'},
            {title: '0800 666 8845', subtitle: 'Oficina Municipal del Consumidor', body: 'Es un canal de ayuda y reclamo en defensa de los derechos de los consumidores.'}
        ]
    },
    {
        tipo: 'personas',
        icono: '../../../../../../assets/img/emergency/pedestrian-accident.png',
        titulo: '¿Qué hacer en caso de un accidente de auto?',
        contenido: [
            {title: 'Primeros pasos', subtitle: 'Inmediatamente después de un accidente', body: '- Detené el auto, apagá el motor y encendé las balizas. Tené en cuenta que abandonar el lugar es un delito. <br>- Si alguna persona se lastimó, ya sea en tu auto como en algún otro involucrado, llamá de inmediato al servicio de emergencias médicas (107), y comunicate también con la policía (911) y los bomberos (100). <br>- Intercambiá información con los conductores de los vehículos involucrados en el siniestro. Es importante tener en cuenta que si se trata de un choque en cadena, deberás pedirle los datos a todos los involucrados, no solo con el que tuviste el choque directo. Solicitá nombre y apellido, número de DNI, dirección y número de teléfono. Además, anotá la patente del vehículo o los vehículos involucrados, el nombre de la compañía de seguros y el número y fecha de vencimiento de la póliza. <br>- Registrá también las condiciones de manejo y la ubicación en la que ocurrió, el tipo de daño causado en ambos vehículos, la marca, el modelo y el año de los vehículos. Si es posible hacerlo, sacá fotos de los daños. <br>- Si el otro conductor abandona el lugar sin compartir sus datos, o si creés que no tiene seguro de auto o está bajo la influencia de drogas o alcohol, llamá de inmediato a la policía (911).'},
            {title: 'Pasos a seguir', subtitle: 'Cómo determinar quién es responsable', body: 'No siempre está claro quién tuvo la culpa en un accidente. Sin embargo, comprenderlo es fundamental para determinar quién o qué compañía se hará cargo de los daños. En cualquier caso, es muy importante que informes a tu compañía de seguros lo que sucedió dentro de las 72hs que ocurrió el accidente. A continuación, te mostramos algunas situaciones que pueden surgir y cómo gestionarlas. <br><br><b>- Situación 1: Si sos culpable</b><br>Si sos culpable del siniestro y el otro conductor está de acuerdo, el proceso es sencillo. Debés contactarte con tu compañía de seguros para hacer la denuncia y relatar cómo fue la situación. Una vez realizada esta denuncia, el tercero va a tener la posibilidad de efectuar el reclamo para cubrir los daños de su auto. Recordá que si tuviste daños en tu vehículo, su reparación o cobro para arreglarlo, dependerá si tenés cobertura de daños por accidente. <br><br><b>- Situación 2: La culpa es del otro conductor</b><br>En el caso de que la culpa sea del otro conductor, deberás proporcionar todos los detalles que puedas a tu compañía de seguros para demostrar que no tuviste la culpa. Si tu aseguradora y la del otro conductor están de acuerdo, la compañía de seguros del otro conductor deberá cubrir el costo de las reparaciones de tu auto. <br><br><b>- Situación 3: Si un conductor no es el propietario</b><br>Si el conductor del vehículo está autorizado a conducir, el seguro del propietario de póliza cubrirá cualquier reclamo de siniestro. Si el conductor está autorizado a conducir ese vehículo, la compañía de seguros del propietario del vehículo se hará cargo de los daños de tu vehículo, siempre que la culpa del siniestro no sea tuya. <br><br><b>- Situación 4: Si ambos conductores tienen la culpa</b><br>En este caso, el costo de los daños se comparte entre los conductores. Sin embargo, el grado de responsabilidad de cada conductor puede no ser el mismo. Por ese motivo, las aseguradoras decidirán cómo se asignará la indemnización. <br><br><b>- Situación 5: Daños al vehículo mientras está estacionado</b><br>Si tu auto tiene daños y el conductor responsable no dejó sus datos, la posibilidad de presentar un reclamo de siniestro al seguro dependerá de tu cobertura. En general, solo la cobertura contra todo riesgo te protege en estas situaciones. <br>En caso de que hayas sido vos quien chocó un auto estacionado, dejale tus datos en el parabrisas para que el dueño del vehículo pueda ponerse en contacto y realizar la denuncia. Recordá que la otra persona depende de eso para avanzar con el reclamo. <br>Ante cualquier duda frente a un siniestro, es importante que te contactes con tu compañía de seguros por asesoramiento. No importa si se trata de un siniestros pequeño o más grande, siempre están para ayudarte. Sea por responsabilidad tuya o por causas ajenas a tu control, es fundamental que estés bien protegido. Tu tranquilidad lo vale.'}
        ]
    },
    {
        tipo: 'personas',
        icono: '../../../../../../assets/img/emergency/fade-out.png',
        titulo: '¿Qué hacer en caso de un desmayo?',
        contenido: [
            {title: 'Riesgos de un desmayo', subtitle: '', body: 'Cuando una persona se desmaya, pierde de manera súbita la conciencia y se desvanece, pero no deja de respirar. El principal riesgo que puede producirse es que se golpee al perder la estabilidad o caerse.'},
            {title: 'Síntomas y causas', subtitle: '', body: 'Algunos síntomas previos al desmayo son: <br>&nbsp;&nbsp;&bull; &nbsp;Debilidad repentina (presión muy baja)<br>&nbsp;&nbsp;&bull; &nbsp;Piel muy pálida<br>&nbsp;&nbsp;&bull; &nbsp;Sudor frío<br>&nbsp;&nbsp;&bull; &nbsp;Vista borrosa<br><br>Le puede ocurrir a personas que no tienen ninguna enfermedad ni condición especial por muchos y diversos motivos:<br>&nbsp;&nbsp;&bull; &nbsp;Por una emoción fuerte.<br>&nbsp;&nbsp;&bull; &nbsp;Por estar en un lugar sin ventilar.<br>&nbsp;&nbsp;&bull; &nbsp;Por tener un ataque de pánico o ansiedad.<br>&nbsp;&nbsp;&bull; &nbsp;Porque está en ayunas.<br>&nbsp;&nbsp;&bull; &nbsp;Por un golpe de calor.<br>&nbsp;&nbsp;&bull; &nbsp;Por una fobia.'},
            {title: 'Qué podés hacer?', subtitle: '', body: '&nbsp;&nbsp;&bull; &nbsp;Comprobá que la persona respira, para saber que lo que sufrió es un desmayo.<br>&nbsp;&nbsp;&bull; &nbsp;Verificá que la persona no se haya golpeado, en especial en la cabeza, y que no haya sufrido cortes o fracturas.<br>&nbsp;&nbsp;&bull; &nbsp;Fijate si perdió el conocimiento o parece como perdida o confundida.<br>&nbsp;&nbsp;&bull; &nbsp;Si la persona respira y no está lastimada ni golpeada, movela a un lugar con buena ventilación.<br>&nbsp;&nbsp;&bull; &nbsp;Si se desmayó en un lugar muy caluroso, llevala a un lugar fresco o a la sombra. Si se desmayó en un lugar frío, ponele un abrigo encima para que no le baje la temperatura del cuerpo.<br>&nbsp;&nbsp;&bull; &nbsp;Si perdió el conocimiento, acostala sobre el piso, aflojale la ropa (botones o cierres del cuello, corbatas) y colocale los pies sobre un objeto alto (el asiento de una silla, una pila de bolsos, una caja), de manera que sus piernas queden elevadas y la presión sanguínea suba.<br>&nbsp;&nbsp;&bull; &nbsp;Si no perdió el conocimiento, acostala boca arriba sobre el piso, aflojale la ropa y pedile que tosa varias veces.<br>&nbsp;&nbsp;&bull; &nbsp;Hasta que no esté totalmente recuperada, no le ofrezcas comidas ni bebidas. Cuando se recupere, ofrecele agua, nunca una bebida alcohólica.<br>&nbsp;&nbsp;&bull; &nbsp;Acompañala hasta que se recupere.'},
            {title: 'Tené también en cuenta', subtitle: '', body: '&nbsp;&nbsp;&bull; &nbsp;Si el desmayo dura más de 5 minutos, llamá a emergencias. Puede tener otra condición que le produjo el desmayo y que no sabemos qué es.<br>&nbsp;&nbsp;&bull; &nbsp;Si tiene <b>convulsiones</b>, puede ser que tenga una crisis epiléptica.<br>&nbsp;&nbsp;&bull; &nbsp;En el caso de <b>embarazadas y de adultos mayores</b>, tenés que prestar especial atención. Las embarazadas, porque pueden sufrir un golpe que afecte su estado. Los adultos mayores, porque pueden desmayarse por otras complicaciones relacionadas con la edad: antecedentes cardíacos, de presión alta o baja, neurológicos, diabetes, deshidratación u otros.'}
        ]
    },
    {
        tipo: 'personas',
        icono: '../../../../../../assets/img/emergency/acv.png',
        titulo: '¿Qué hacer en caso de sufrir un ACV (Accidente cerebro vascular?',
        contenido: [
            {title: 'Qué es un ACV?', subtitle: '', body: 'El ACV es una enfermedad aguda que se produce cuando se tapa o rompe una arteria del cerebro. Puede ser mortal o dejar a la persona afectada con una discapacidad.<br><b>Cada segundo es vital para ayudar a quien sufre un ACV!</b>'},
            {title: 'Cuáles son los síntomas?', subtitle: '', body: '&nbsp;&nbsp;&bull; &nbsp;Los síntomas pueden ser diferentes y muy sutiles:<br>&nbsp;&nbsp;&bull; &nbsp;Debilidad o sensación de que se duerme un lado de la cara, un brazo o una pierna, especialmente del mismo costado.<br>&nbsp;&nbsp;&bull; &nbsp;Confusión al hablar.<br>&nbsp;&nbsp;&bull; &nbsp;Problemas para hablar o entender lo que se le dice.<br>&nbsp;&nbsp;&bull; &nbsp;Problemas para caminar.<br>&nbsp;&nbsp;&bull; &nbsp;Mareos.<br>&nbsp;&nbsp;&bull; &nbsp;Pérdida de equilibrio o falta de coordinación del cuerpo (por ejemplo, querer agarrar algo y no poder).<br>&nbsp;&nbsp;&bull; &nbsp;Dolor de cabeza muy fuerte y repentino.'},
            {title: 'Qué podés hacer?', subtitle: '', body: '&nbsp;&nbsp;&bull; &nbsp;Comprobá si la persona tiene dificultades para entender o hablar. Hablale para ver si te entiende y responde a tus órdenes.<br>&nbsp;&nbsp;&bull; &nbsp;No dejes sola a la persona. Tranquilizala y mantenete tranquilo.<br>&nbsp;&nbsp;&bull; &nbsp;Llamá a Emergencias(107) o llevala a una guardia médica si está cerca.<br>&nbsp;&nbsp;&bull; &nbsp;Cuanto más rápido reciba asistencia médica, aumentan las probabilidades de que la persona se recupere y/o solo le queden secuelas leves.'},
            {title: 'Prevení el ACV', subtitle: '', body: '&nbsp;&nbsp;&bull; &nbsp;<b>Un control anual</b> va a servirle a tu médico para saber si tenés riesgo de sufrir un ACV y ayudarte a reducirlo.<br>&nbsp;&nbsp;&bull; &nbsp;<b>Adoptá los hábitos saludables</b> que te aconseje el médico: actividad física sostenida, alimentación sana, consumo de frutas y verduras, y reducir el consumo de sal, entre otros.'}
        ]
    },

 ]